name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js (v15.x)
      uses: actions/setup-node@v4
      with:
        node-version: '15.x'  # Instalar versão 15.x para compatibilidade com seu package.json

    - name: Install Dependencies
      run: |
        npm install

    - name: Linter (ESLint)
      run: |
        npm run lint

    - name: Formatter (Prettier)
      run: |
        npm run prettier

    - name: Test (Jest)
      run: |
        CI=true npm run test

    - name: Build
      run: |
        npm run build

    - name: Docker Build and Push
      run: |
        docker build -t meu-app:latest .
        docker push meu-usuario/meu-app:latest  # Se usar Docker Hub
