name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js (v15.x)
      uses: actions/setup-node@v4
      with:
        node-version: '15.x'  # Instalar versão 15.x para compatibilidade com seu package.json

    - name: Install Dependencies
      run: |
        cd codebase/rdicidr-0.1.0
        npm install

    - name: Linter (ESLint)
      run: |
        cd codebase/rdicidr-0.1.0
        npm run lint

    - name: Formatter (Prettier)
      run: |
        cd codebase/rdicidr-0.1.0
        npm run prettier

    - name: Test (Jest)
      run: |
        cd codebase/rdicidr-0.1.0
        CI=true npm run test

    - name: Build
      run: |
        cd codebase/rdicidr-0.1.0
        npm run build